### PR TITLE
Pull from upstream

### PR DESCRIPTION
**Pull request by MasterOfTheTiger**

### CODE REVIEW

**Comment by MasterOfTheTiger** [comment]
Too much conflicts. :/

**Comment by Jackymancs4** [comment]
Hello @MasterOfTheTiger 
Can you share what prevented this from landing?
Would you like any help?

Right now the Firefox fork is more than month behind Chrome. Usually is not a problem, but yesterday landed a quite useful feature (hide retweet) that I'd love to see in Firefox.

**Comment by MasterOfTheTiger** [comment]
I need to figure out a better way to do this. I might have some time later to work on it. 

The problem is that this has way too many merge conflicts. I might have to make a new repo for this soon and work on it differently. 

The only changes made in this fork from the upstream is the names, so I don't know why there are so many conflicts.

**Comment by MasterOfTheTiger** [comment]
I fixed it all.

**Comment by MasterOfTheTiger** [comment]
New version will be released soon.

**Comment by MasterOfTheTiger** [comment]
The new version is released and works great! @Jackymancs4

**Comment by Jackymancs4** [comment]
Awesome, thank you very much!
As a side note, would it be a problem for you to enable issues also in this repo?
A [guide](https://softwareengineering.stackexchange.com/a/179470) if needed.

This way for update requests or for reporting issues for Firefox nobody will bother upstream, which doesn't offer direct support to it.

**Comment by MasterOfTheTiger** [comment]
Yeah. I was thinking about that. I just added them now. (I didn't need the guide).

**Pull request closed without merging**
